/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rgbszdjyubbxhzhspuqv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnYnN6ZGp5dWJieGh6aHNwdXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc3MDU4MzMsImV4cCI6MjA5MzI4MTgzM30.y-9yb6tKrjlCI43fIT_XtDnUEcqLuA_7hVlg5-wvE80"